export type AliasSeed = { alias_key: string; canonical_lookup_key: string; alias: string; locale?: string; language?: string; alias_type?: string };

export const CURATED_PT_ALIASES: AliasSeed[] = [
  ['supino_reto', 'barbell_bench_press'],
  ['supino_reto_barra', 'barbell_bench_press'],
  ['supino_com_barra', 'barbell_bench_press'],
  ['supino_inclinado', 'incline_barbell_bench_press'],
  ['supino_inclinado_halteres', 'incline_dumbbell_press'],
  ['puxada_frente', 'lat_pulldown'],
  ['puxada_frontal', 'lat_pulldown'],
  ['barra_fixa', 'pull_up'],
  ['barra_fixa_pronada', 'pull_up'],
  ['barra_fixa_supinada', 'chin_up'],
  ['desenvolvimento_militar', 'shoulder_press'],
  ['remada_curvada', 'bent_over_row'],
  ['remada_baixa', 'seated_cable_row'],
  ['levantamento_terra', 'deadlift'],
  ['stiff', 'stiff_leg_deadlift'],
  ['triceps_pulley', 'triceps_pushdown'],
  ['triceps_corda', 'triceps_pushdown_rope_attachment'],
  ['rosca_direta', 'barbell_curl'],
  ['rosca_martelo', 'hammer_curl'],
  ['elevacao_lateral', 'lateral_raise'],
  ['crucifixo', 'dumbbell_fly'],
  ['passada', 'lunge'],
  ['avanco', 'lunge'],
  ['panturrilha_em_pe', 'standing_calf_raise'],
  ['abdominal', 'crunch'],
].map(([alias_key, canonical_lookup_key]) => ({ alias_key, canonical_lookup_key, alias: alias_key.replace(/_/g, ' '), locale: 'pt_BR', language: 'pt', alias_type: 'synonym' }));
