'use strict';

// KRONIA Food Database
// Each food entry contains the full field set required by the KRONIA diet engine.
// Fields: nome, categoria, subcategoria, kcal_por_100g, proteina_por_100g,
//         carbo_por_100g, gordura_por_100g, fibra_por_100g, medida_caseira,
//         grupo_equivalencia, objetivo_indicado, objetivo_evitar,
//         patologias_permitidas, patologias_bloqueadas, prioridade (1-10)

var KRONA_FOODS = [
  // ─── PROTEÍNAS ANIMAIS ───────────────────────────────────────────────────────
  {
    code: 'frango_grelhado',
    taco_id: 'TACO_0410',
    nome: 'Frango grelhado',
    categoria: 'proteina',
    subcategoria: 'magra',
    kcal_por_100g: 165,
    proteina_por_100g: 31,
    carbo_por_100g: 0,
    gordura_por_100g: 3.6,
    fibra_por_100g: 0,
    medida_caseira: '1 filé médio (120 g)',
    grupo_equivalencia: 'proteina_magra',
    objetivo_indicado: ['emagrecimento', 'hipertrofia', 'recomposicao', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia', 'doenca_renal_leve'],
    patologias_bloqueadas: [],
    prioridade: 9
  },
  {
    code: 'peito_peru',
    nome: 'Peito de peru assado',
    categoria: 'proteina',
    subcategoria: 'magra',
    kcal_por_100g: 135,
    proteina_por_100g: 29,
    carbo_por_100g: 0,
    gordura_por_100g: 2.5,
    fibra_por_100g: 0,
    medida_caseira: '4 fatias (80 g)',
    grupo_equivalencia: 'proteina_magra',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 8
  },
  {
    code: 'patinho_grelhado',
    taco_id: 'TACO_0377',
    nome: 'Patinho grelhado',
    categoria: 'proteina',
    subcategoria: 'magra',
    kcal_por_100g: 188,
    proteina_por_100g: 28,
    carbo_por_100g: 0,
    gordura_por_100g: 8.3,
    fibra_por_100g: 0,
    medida_caseira: '1 bife médio (120 g)',
    grupo_equivalencia: 'proteina_magra',
    objetivo_indicado: ['hipertrofia', 'manutencao', 'forca'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao'],
    patologias_bloqueadas: ['dislipidemia'],
    prioridade: 7
  },
  {
    code: 'tilapia_grelhada',
    nome: 'Tilápia grelhada',
    categoria: 'proteina',
    subcategoria: 'magra',
    kcal_por_100g: 128,
    proteina_por_100g: 26,
    carbo_por_100g: 0,
    gordura_por_100g: 2.7,
    fibra_por_100g: 0,
    medida_caseira: '1 filé médio (140 g)',
    grupo_equivalencia: 'proteina_magra',
    objetivo_indicado: ['emagrecimento', 'hipertrofia', 'recomposicao', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia', 'doenca_renal_leve'],
    patologias_bloqueadas: [],
    prioridade: 9
  },
  {
    code: 'salmao_grelhado',
    nome: 'Salmão grelhado',
    categoria: 'proteina',
    subcategoria: 'gordurosa',
    kcal_por_100g: 206,
    proteina_por_100g: 22,
    carbo_por_100g: 0,
    gordura_por_100g: 13,
    fibra_por_100g: 0,
    medida_caseira: '1 posta média (130 g)',
    grupo_equivalencia: 'proteina_gordurosa',
    objetivo_indicado: ['hipertrofia', 'manutencao', 'forca'],
    objetivo_evitar: ['emagrecimento'],
    patologias_permitidas: ['diabetes', 'dislipidemia', 'hipertensao'],
    patologias_bloqueadas: [],
    prioridade: 8
  },
  {
    code: 'atum_lata',
    nome: 'Atum em lata (em água)',
    categoria: 'proteina',
    subcategoria: 'magra',
    kcal_por_100g: 116,
    proteina_por_100g: 25,
    carbo_por_100g: 0,
    gordura_por_100g: 1.4,
    fibra_por_100g: 0,
    medida_caseira: '1 lata (100 g)',
    grupo_equivalencia: 'proteina_magra',
    objetivo_indicado: ['emagrecimento', 'recomposicao', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'dislipidemia'],
    patologias_bloqueadas: ['hipertensao'],
    prioridade: 7
  },
  {
    code: 'ovo_inteiro',
    taco_id: 'TACO_0488',
    nome: 'Ovo inteiro cozido',
    categoria: 'proteina',
    subcategoria: 'mista',
    kcal_por_100g: 155,
    proteina_por_100g: 13,
    carbo_por_100g: 1.1,
    gordura_por_100g: 11,
    fibra_por_100g: 0,
    medida_caseira: '2 unidades (100 g)',
    grupo_equivalencia: 'proteina_cafe',
    objetivo_indicado: ['emagrecimento', 'hipertrofia', 'recomposicao', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao'],
    patologias_bloqueadas: [],
    prioridade: 9
  },
  {
    code: 'clara_ovo',
    nome: 'Claras de ovo',
    categoria: 'proteina',
    subcategoria: 'magra',
    kcal_por_100g: 52,
    proteina_por_100g: 11,
    carbo_por_100g: 0.7,
    gordura_por_100g: 0.2,
    fibra_por_100g: 0,
    medida_caseira: '4 claras (120 g)',
    grupo_equivalencia: 'proteina_cafe',
    objetivo_indicado: ['emagrecimento', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 8
  },

  // ─── PROTEÍNAS LÁCTEAS ───────────────────────────────────────────────────────
  {
    code: 'iogurte_grego',
    nome: 'Iogurte grego natural',
    categoria: 'proteina',
    subcategoria: 'laticinios',
    kcal_por_100g: 97,
    proteina_por_100g: 10,
    carbo_por_100g: 3.6,
    gordura_por_100g: 5,
    fibra_por_100g: 0,
    medida_caseira: '1 pote (170 g)',
    grupo_equivalencia: 'proteina_cafe',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'dislipidemia'],
    patologias_bloqueadas: ['intolerancia_lactose'],
    prioridade: 8
  },
  {
    code: 'cottage',
    nome: 'Cottage',
    categoria: 'proteina',
    subcategoria: 'laticinios',
    kcal_por_100g: 98,
    proteina_por_100g: 11,
    carbo_por_100g: 3.4,
    gordura_por_100g: 4.3,
    fibra_por_100g: 0,
    medida_caseira: '4 col. sopa (100 g)',
    grupo_equivalencia: 'proteina_cafe',
    objetivo_indicado: ['emagrecimento', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'dislipidemia'],
    patologias_bloqueadas: ['intolerancia_lactose'],
    prioridade: 7
  },

  // ─── PROTEÍNAS VEGETAIS ──────────────────────────────────────────────────────
  {
    code: 'tofu_firme',
    nome: 'Tofu firme',
    categoria: 'proteina',
    subcategoria: 'vegetal',
    kcal_por_100g: 96,
    proteina_por_100g: 10,
    carbo_por_100g: 2.5,
    gordura_por_100g: 5.5,
    fibra_por_100g: 1.2,
    medida_caseira: '1 fatia grossa (150 g)',
    grupo_equivalencia: 'proteina_vegetal',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia', 'doenca_renal_leve'],
    patologias_bloqueadas: [],
    prioridade: 8
  },
  {
    code: 'whey_protein',
    nome: 'Whey protein',
    categoria: 'proteina',
    subcategoria: 'suplemento',
    kcal_por_100g: 400,
    proteina_por_100g: 80,
    carbo_por_100g: 10,
    gordura_por_100g: 7,
    fibra_por_100g: 0,
    medida_caseira: '1 scoop (30 g)',
    grupo_equivalencia: 'proteina_suplemento',
    objetivo_indicado: ['hipertrofia', 'recomposicao', 'forca'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'dislipidemia'],
    patologias_bloqueadas: ['intolerancia_lactose', 'doenca_renal_avancada'],
    prioridade: 7
  },

  // ─── CARBOIDRATOS COMPLEXOS ──────────────────────────────────────────────────
  {
    code: 'arroz_branco',
    taco_id: 'TACO_0003',
    nome: 'Arroz cozido',
    categoria: 'carbo',
    subcategoria: 'grao',
    kcal_por_100g: 130,
    proteina_por_100g: 2.5,
    carbo_por_100g: 28,
    gordura_por_100g: 0.3,
    fibra_por_100g: 0.4,
    medida_caseira: '4 col. sopa cheias (120 g)',
    grupo_equivalencia: 'carbo_almoco',
    objetivo_indicado: ['hipertrofia', 'manutencao', 'forca'],
    objetivo_evitar: [],
    patologias_permitidas: ['hipertensao', 'dislipidemia'],
    patologias_bloqueadas: ['diabetes'],
    prioridade: 7
  },
  {
    code: 'arroz_integral',
    taco_id: 'TACO_0001',
    nome: 'Arroz integral cozido',
    categoria: 'carbo',
    subcategoria: 'grao',
    kcal_por_100g: 123,
    proteina_por_100g: 2.6,
    carbo_por_100g: 25,
    gordura_por_100g: 0.9,
    fibra_por_100g: 1.8,
    medida_caseira: '4 col. sopa cheias (120 g)',
    grupo_equivalencia: 'carbo_almoco',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 9
  },
  {
    code: 'batata_doce',
    taco_id: 'TACO_0088',
    nome: 'Batata-doce cozida',
    categoria: 'carbo',
    subcategoria: 'tuberculo',
    kcal_por_100g: 86,
    proteina_por_100g: 1.6,
    carbo_por_100g: 20,
    gordura_por_100g: 0.1,
    fibra_por_100g: 3,
    medida_caseira: '1 unidade média (130 g)',
    grupo_equivalencia: 'carbo_almoco',
    objetivo_indicado: ['emagrecimento', 'hipertrofia', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['dislipidemia', 'hipertensao'],
    patologias_bloqueadas: ['alto_potassio'],
    prioridade: 9
  },
  {
    code: 'batata_inglesa',
    taco_id: 'TACO_0091',
    nome: 'Batata inglesa cozida',
    categoria: 'carbo',
    subcategoria: 'tuberculo',
    kcal_por_100g: 77,
    proteina_por_100g: 2,
    carbo_por_100g: 17,
    gordura_por_100g: 0.1,
    fibra_por_100g: 2.2,
    medida_caseira: '1 unidade média (150 g)',
    grupo_equivalencia: 'carbo_almoco',
    objetivo_indicado: ['manutencao', 'hipertrofia'],
    objetivo_evitar: [],
    patologias_permitidas: ['hipertensao', 'dislipidemia'],
    patologias_bloqueadas: ['diabetes'],
    prioridade: 6
  },
  {
    code: 'macarrao_cozido',
    // Sem correspondência segura direta na TACO 4ª edição para a forma genérica "cozido".
    nome: 'Macarrão cozido',
    categoria: 'carbo',
    subcategoria: 'massa',
    kcal_por_100g: 157,
    proteina_por_100g: 5,
    carbo_por_100g: 31,
    gordura_por_100g: 1,
    fibra_por_100g: 1.8,
    medida_caseira: '1 xícara (120 g)',
    grupo_equivalencia: 'carbo_almoco',
    objetivo_indicado: ['hipertrofia', 'manutencao'],
    objetivo_evitar: ['emagrecimento'],
    patologias_permitidas: ['hipertensao'],
    patologias_bloqueadas: ['diabetes', 'gluten'],
    prioridade: 5
  },
  {
    code: 'quinoa',
    nome: 'Quinoa cozida',
    categoria: 'carbo',
    subcategoria: 'grao',
    kcal_por_100g: 120,
    proteina_por_100g: 4.4,
    carbo_por_100g: 21,
    gordura_por_100g: 1.9,
    fibra_por_100g: 2.8,
    medida_caseira: '4 col. sopa (100 g)',
    grupo_equivalencia: 'carbo_almoco',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia', 'gluten'],
    patologias_bloqueadas: [],
    prioridade: 9
  },

  // ─── CARBOIDRATOS CAFÉ DA MANHÃ ──────────────────────────────────────────────
  {
    code: 'aveia',
    taco_id: 'TACO_0007',
    nome: 'Aveia em flocos',
    categoria: 'carbo',
    subcategoria: 'cereal',
    kcal_por_100g: 389,
    proteina_por_100g: 17,
    carbo_por_100g: 66,
    gordura_por_100g: 7,
    fibra_por_100g: 10.6,
    medida_caseira: '4 col. sopa (40 g)',
    grupo_equivalencia: 'carbo_cafe',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: ['gluten_severo'],
    prioridade: 10
  },
  {
    code: 'pao_integral',
    taco_id: 'TACO_0052',
    nome: 'Pão integral',
    categoria: 'carbo',
    subcategoria: 'pao',
    kcal_por_100g: 247,
    proteina_por_100g: 8.5,
    carbo_por_100g: 41,
    gordura_por_100g: 3.4,
    fibra_por_100g: 7,
    medida_caseira: '2 fatias (50 g)',
    grupo_equivalencia: 'carbo_cafe',
    objetivo_indicado: ['manutencao', 'hipertrofia'],
    objetivo_evitar: [],
    patologias_permitidas: ['hipertensao'],
    patologias_bloqueadas: ['diabetes', 'gluten'],
    prioridade: 6
  },
  {
    code: 'tapioca',
    // A TACO 4ª edição traz variantes como "Tapioca, com manteiga"; não há mapeamento genérico seguro para a base do KroniA.
    nome: 'Tapioca',
    categoria: 'carbo',
    subcategoria: 'cereal',
    kcal_por_100g: 240,
    proteina_por_100g: 0.4,
    carbo_por_100g: 60,
    gordura_por_100g: 0,
    fibra_por_100g: 0.2,
    medida_caseira: '2 col. sopa (70 g)',
    grupo_equivalencia: 'carbo_cafe',
    objetivo_indicado: ['hipertrofia', 'manutencao'],
    objetivo_evitar: ['emagrecimento'],
    patologias_permitidas: ['hipertensao', 'gluten'],
    patologias_bloqueadas: ['diabetes'],
    prioridade: 6
  },

  // ─── LEGUMINOSAS ─────────────────────────────────────────────────────────────
  {
    code: 'feijao_cozido',
    taco_id: 'TACO_0561',
    nome: 'Feijão cozido',
    categoria: 'leguminosa',
    subcategoria: 'leguminosa',
    kcal_por_100g: 76,
    proteina_por_100g: 4.8,
    carbo_por_100g: 13.6,
    gordura_por_100g: 0.5,
    fibra_por_100g: 8.5,
    medida_caseira: '1 concha (100 g)',
    grupo_equivalencia: 'leguminosa',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: ['doenca_renal_avancada'],
    prioridade: 9
  },
  {
    code: 'lentilha_cozida',
    nome: 'Lentilha cozida',
    categoria: 'leguminosa',
    subcategoria: 'leguminosa',
    kcal_por_100g: 116,
    proteina_por_100g: 9,
    carbo_por_100g: 20,
    gordura_por_100g: 0.4,
    fibra_por_100g: 8,
    medida_caseira: '1 concha (100 g)',
    grupo_equivalencia: 'leguminosa',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: ['doenca_renal_avancada'],
    prioridade: 9
  },
  {
    code: 'grao_de_bico',
    nome: 'Grão-de-bico cozido',
    categoria: 'leguminosa',
    subcategoria: 'leguminosa',
    kcal_por_100g: 164,
    proteina_por_100g: 8.9,
    carbo_por_100g: 27,
    gordura_por_100g: 2.6,
    fibra_por_100g: 7.6,
    medida_caseira: '1 concha (100 g)',
    grupo_equivalencia: 'leguminosa',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: ['doenca_renal_avancada'],
    prioridade: 8
  },

  // ─── GORDURAS SAUDÁVEIS ──────────────────────────────────────────────────────
  {
    code: 'azeite_oliva',
    nome: 'Azeite de oliva',
    categoria: 'gordura',
    subcategoria: 'oleo',
    kcal_por_100g: 884,
    proteina_por_100g: 0,
    carbo_por_100g: 0,
    gordura_por_100g: 100,
    fibra_por_100g: 0,
    medida_caseira: '1 col. sopa (10 ml)',
    grupo_equivalencia: 'gordura_boa',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 10
  },
  {
    code: 'abacate',
    nome: 'Abacate',
    categoria: 'gordura',
    subcategoria: 'fruta_gordurosa',
    kcal_por_100g: 160,
    proteina_por_100g: 2,
    carbo_por_100g: 9,
    gordura_por_100g: 15,
    fibra_por_100g: 6.7,
    medida_caseira: '1/2 unidade (100 g)',
    grupo_equivalencia: 'gordura_boa',
    objetivo_indicado: ['manutencao', 'hipertrofia'],
    objetivo_evitar: ['emagrecimento'],
    patologias_permitidas: ['diabetes', 'dislipidemia'],
    patologias_bloqueadas: ['alto_potassio'],
    prioridade: 7
  },
  {
    code: 'pasta_amendoim',
    nome: 'Pasta de amendoim',
    categoria: 'gordura',
    subcategoria: 'oleaginosa',
    kcal_por_100g: 590,
    proteina_por_100g: 25,
    carbo_por_100g: 20,
    gordura_por_100g: 50,
    fibra_por_100g: 6,
    medida_caseira: '1 col. sopa (20 g)',
    grupo_equivalencia: 'gordura_cafe',
    objetivo_indicado: ['hipertrofia', 'manutencao'],
    objetivo_evitar: ['emagrecimento'],
    patologias_permitidas: ['diabetes', 'dislipidemia'],
    patologias_bloqueadas: ['alergia_amendoim'],
    prioridade: 7
  },
  {
    code: 'castanhas',
    nome: 'Castanhas mistas',
    categoria: 'gordura',
    subcategoria: 'oleaginosa',
    kcal_por_100g: 607,
    proteina_por_100g: 15,
    carbo_por_100g: 21,
    gordura_por_100g: 54,
    fibra_por_100g: 7,
    medida_caseira: '1 punhado (20 g)',
    grupo_equivalencia: 'gordura_boa',
    objetivo_indicado: ['manutencao', 'hipertrofia'],
    objetivo_evitar: ['emagrecimento'],
    patologias_permitidas: ['diabetes', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 8
  },
  {
    code: 'chia',
    nome: 'Sementes de chia',
    categoria: 'gordura',
    subcategoria: 'semente',
    kcal_por_100g: 486,
    proteina_por_100g: 17,
    carbo_por_100g: 42,
    gordura_por_100g: 31,
    fibra_por_100g: 34,
    medida_caseira: '1 col. sopa (15 g)',
    grupo_equivalencia: 'gordura_cafe',
    objetivo_indicado: ['emagrecimento', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 9
  },

  // ─── FRUTAS ──────────────────────────────────────────────────────────────────
  {
    code: 'banana',
    taco_id: 'TACO_0182',
    nome: 'Banana',
    categoria: 'fruta',
    subcategoria: 'energetica',
    kcal_por_100g: 89,
    proteina_por_100g: 1.1,
    carbo_por_100g: 23,
    gordura_por_100g: 0.3,
    fibra_por_100g: 2.6,
    medida_caseira: '1 unidade média (90 g)',
    grupo_equivalencia: 'fruta_energetica',
    objetivo_indicado: ['hipertrofia', 'manutencao', 'forca'],
    objetivo_evitar: ['emagrecimento'],
    patologias_permitidas: ['dislipidemia', 'hipertensao'],
    patologias_bloqueadas: ['alto_potassio', 'diabetes'],
    prioridade: 7
  },
  {
    code: 'maca',
    taco_id: 'TACO_0221',
    nome: 'Maçã',
    categoria: 'fruta',
    subcategoria: 'neutra',
    kcal_por_100g: 52,
    proteina_por_100g: 0.3,
    carbo_por_100g: 14,
    gordura_por_100g: 0.2,
    fibra_por_100g: 2.4,
    medida_caseira: '1 unidade média (130 g)',
    grupo_equivalencia: 'fruta_neutra',
    objetivo_indicado: ['emagrecimento', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 9
  },
  {
    code: 'frutas_vermelhas',
    nome: 'Frutas vermelhas',
    categoria: 'fruta',
    subcategoria: 'baixo_ig',
    kcal_por_100g: 50,
    proteina_por_100g: 0.7,
    carbo_por_100g: 11.4,
    gordura_por_100g: 0.3,
    fibra_por_100g: 4,
    medida_caseira: '1 xícara (140 g)',
    grupo_equivalencia: 'fruta_neutra',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 10
  },

  // ─── VEGETAIS ────────────────────────────────────────────────────────────────
  {
    code: 'brocolis',
    nome: 'Brócolis cozido',
    categoria: 'vegetal',
    subcategoria: 'crucifero',
    kcal_por_100g: 25,
    proteina_por_100g: 3,
    carbo_por_100g: 4.4,
    gordura_por_100g: 0.5,
    fibra_por_100g: 3.4,
    medida_caseira: '1 xícara (100 g)',
    grupo_equivalencia: 'vegetal_crucifero',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: ['hipotireoidismo_severo'],
    prioridade: 10
  },
  {
    code: 'salada_verde',
    nome: 'Salada verde',
    categoria: 'vegetal',
    subcategoria: 'folha',
    kcal_por_100g: 20,
    proteina_por_100g: 1.5,
    carbo_por_100g: 3,
    gordura_por_100g: 0.3,
    fibra_por_100g: 2,
    medida_caseira: '1 prato raso (100 g)',
    grupo_equivalencia: 'vegetal_folha',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia', 'recomposicao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 10
  },
  {
    code: 'legumes_cozidos',
    nome: 'Legumes cozidos',
    categoria: 'vegetal',
    subcategoria: 'legume',
    kcal_por_100g: 35,
    proteina_por_100g: 1.5,
    carbo_por_100g: 7,
    gordura_por_100g: 0.3,
    fibra_por_100g: 2.8,
    medida_caseira: '1 xícara (100 g)',
    grupo_equivalencia: 'vegetal_legume',
    objetivo_indicado: ['emagrecimento', 'manutencao', 'hipertrofia'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 9
  },
  {
    code: 'cenoura',
    nome: 'Cenoura cozida',
    categoria: 'vegetal',
    subcategoria: 'legume',
    kcal_por_100g: 35,
    proteina_por_100g: 0.8,
    carbo_por_100g: 8.2,
    gordura_por_100g: 0.2,
    fibra_por_100g: 2.9,
    medida_caseira: '1 unidade média (100 g)',
    grupo_equivalencia: 'vegetal_legume',
    objetivo_indicado: ['emagrecimento', 'manutencao'],
    objetivo_evitar: [],
    patologias_permitidas: ['diabetes', 'hipertensao', 'dislipidemia'],
    patologias_bloqueadas: [],
    prioridade: 8
  }
];

// Index foods by code for fast lookup
var FOOD_INDEX = KRONA_FOODS.reduce(function(acc, food) {
  acc[food.code] = food;
  return acc;
}, {});

// Group foods by equivalence group
var EQUIVALENCE_GROUPS = KRONA_FOODS.reduce(function(acc, food) {
  var g = food.grupo_equivalencia;
  if (!acc[g]) acc[g] = [];
  acc[g].push(food);
  return acc;
}, {});

// Group foods by category
var CATEGORY_INDEX = KRONA_FOODS.reduce(function(acc, food) {
  var c = food.categoria;
  if (!acc[c]) acc[c] = [];
  acc[c].push(food);
  return acc;
}, {});

function getFoodByCode(code) {
  return FOOD_INDEX[code] || null;
}

function getFoodsByCategory(categoria) {
  return (CATEGORY_INDEX[categoria] || []).slice();
}

function getFoodsByEquivalenceGroup(grupo) {
  return (EQUIVALENCE_GROUPS[grupo] || []).slice();
}

function getAllFoods() {
  return KRONA_FOODS.slice();
}

module.exports = {
  KRONA_FOODS: KRONA_FOODS,
  FOOD_INDEX: FOOD_INDEX,
  EQUIVALENCE_GROUPS: EQUIVALENCE_GROUPS,
  CATEGORY_INDEX: CATEGORY_INDEX,
  getFoodByCode: getFoodByCode,
  getFoodsByCategory: getFoodsByCategory,
  getFoodsByEquivalenceGroup: getFoodsByEquivalenceGroup,
  getAllFoods: getAllFoods
};
