-- KRONIA Observability & Diagnóstico Administrativo
-- Seguro para produção: criação idempotente + RLS ativo.

create extension if not exists pgcrypto;

create table if not exists public.diagnostic_admin_whitelist (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.diagnostic_executions (
  id bigint generated by default as identity primary key,
  execution_id uuid not null unique,
  user_id uuid null,
  session_id text null,
  is_admin_mode boolean not null default false,
  source text not null default 'chat',
  input_type text null,
  raw_input_summary text null,
  normalized_input_summary text null,
  intent_detected text null,
  intent_confidence numeric(6,5) null,
  pipeline_selected text null,
  decision_reason text null,
  fallback_used boolean not null default false,
  started_at timestamptz not null default now(),
  finished_at timestamptz null,
  duration_ms integer null,
  success boolean null,
  final_status text not null default 'running',
  error_code text null,
  error_message text null,
  response_summary text null,
  graph_path text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.diagnostic_steps (
  id bigint generated by default as identity primary key,
  execution_id uuid not null,
  step_order integer not null,
  layer text not null default 'application',
  node_key text null,
  step_name text not null,
  status text not null default 'running',
  input_summary text null,
  output_summary text null,
  decision_reason text null,
  duration_ms integer null,
  success boolean null,
  error_code text null,
  error_message text null,
  prompt_signature text null,
  context_summary text null,
  dependency_summary text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint diagnostic_steps_execution_fk
    foreign key (execution_id)
    references public.diagnostic_executions(execution_id)
    on delete cascade,
  constraint diagnostic_steps_execution_order_unique unique (execution_id, step_order)
);

create index if not exists idx_diag_exec_execution_id on public.diagnostic_executions(execution_id);
create index if not exists idx_diag_exec_user_id on public.diagnostic_executions(user_id);
create index if not exists idx_diag_exec_created_at on public.diagnostic_executions(created_at desc);
create index if not exists idx_diag_exec_final_status on public.diagnostic_executions(final_status);
create index if not exists idx_diag_exec_pipeline_selected on public.diagnostic_executions(pipeline_selected);
create index if not exists idx_diag_exec_intent_detected on public.diagnostic_executions(intent_detected);
create index if not exists idx_diag_exec_success on public.diagnostic_executions(success);
create index if not exists idx_diag_steps_execution_id on public.diagnostic_steps(execution_id);
create index if not exists idx_diag_steps_node_key on public.diagnostic_steps(node_key);
create index if not exists idx_diag_steps_created_at on public.diagnostic_steps(created_at desc);

create or replace function public.set_diagnostic_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_diagnostic_executions_updated_at on public.diagnostic_executions;
create trigger trg_diagnostic_executions_updated_at
before update on public.diagnostic_executions
for each row execute function public.set_diagnostic_updated_at();

create or replace function public.kronia_is_diagnostic_admin()
returns boolean
language sql
stable
as $$
  select
    coalesce(
      exists(
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and lower(coalesce(p.role::text, '')) in ('admin', 'owner')
      ),
      false
    )
    or lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) in ('admin', 'owner')
    or exists(
      select 1
      from public.diagnostic_admin_whitelist w
      where lower(w.email) = lower(coalesce(auth.jwt() ->> 'email', auth.email()))
    );
$$;

alter table public.diagnostic_executions enable row level security;
alter table public.diagnostic_steps enable row level security;
alter table public.diagnostic_admin_whitelist enable row level security;

-- backend usa service_role (bypass RLS). para usuários autenticados, leitura apenas admin.
drop policy if exists diagnostic_executions_admin_read on public.diagnostic_executions;
create policy diagnostic_executions_admin_read
on public.diagnostic_executions
for select
to authenticated
using (public.kronia_is_diagnostic_admin());

drop policy if exists diagnostic_executions_admin_insert on public.diagnostic_executions;
create policy diagnostic_executions_admin_insert
on public.diagnostic_executions
for insert
to authenticated
with check (public.kronia_is_diagnostic_admin());

drop policy if exists diagnostic_steps_admin_read on public.diagnostic_steps;
create policy diagnostic_steps_admin_read
on public.diagnostic_steps
for select
to authenticated
using (public.kronia_is_diagnostic_admin());

drop policy if exists diagnostic_steps_admin_insert on public.diagnostic_steps;
create policy diagnostic_steps_admin_insert
on public.diagnostic_steps
for insert
to authenticated
with check (public.kronia_is_diagnostic_admin());

drop policy if exists diagnostic_whitelist_admin_read on public.diagnostic_admin_whitelist;
create policy diagnostic_whitelist_admin_read
on public.diagnostic_admin_whitelist
for select
to authenticated
using (public.kronia_is_diagnostic_admin());

create or replace view public.diagnostic_execution_health as
select
  coalesce(pipeline_selected, 'unknown') as component,
  count(*) as total,
  sum(case when success = true then 1 else 0 end) as success_total,
  sum(case when success = false then 1 else 0 end) as failure_total,
  round(avg(nullif(duration_ms, 0)))::int as avg_duration_ms,
  max(created_at) as last_execution_at,
  round(
    case when count(*) = 0 then 1
         else sum(case when success = true then 1 else 0 end)::numeric / count(*)::numeric
    end
  , 4) as success_rate,
  case
    when count(*) = 0 then 'inactive'
    when (sum(case when success = false then 1 else 0 end)::numeric / greatest(count(*)::numeric, 1)) >= 0.4 then 'failing'
    when (sum(case when success = false then 1 else 0 end)::numeric / greatest(count(*)::numeric, 1)) >= 0.15 then 'degraded'
    else 'healthy'
  end as status
from public.diagnostic_executions
where created_at >= now() - interval '24 hours'
group by 1;

grant select on public.diagnostic_execution_health to authenticated;
