-- KRONIA INTELLIGENCE: observabilidade interna desacoplada do chat principal.

create table if not exists public.kronia_intelligence_events (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  module text not null,
  action text not null,
  event text not null,
  severity text not null default 'low',
  problem_code text null,
  problem_label text null,
  analysis text null,
  recommendation text null,
  task text null,
  correlation_id text null,
  source text not null default 'client',
  app_version text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_kronia_intelligence_created_at on public.kronia_intelligence_events(created_at desc);
create index if not exists idx_kronia_intelligence_module on public.kronia_intelligence_events(module);
create index if not exists idx_kronia_intelligence_event on public.kronia_intelligence_events(event);
create index if not exists idx_kronia_intelligence_problem_code on public.kronia_intelligence_events(problem_code);
create index if not exists idx_kronia_intelligence_correlation on public.kronia_intelligence_events(correlation_id);

alter table public.kronia_intelligence_events enable row level security;

drop policy if exists kronia_intelligence_admin_read on public.kronia_intelligence_events;
create policy kronia_intelligence_admin_read
on public.kronia_intelligence_events
for select
to authenticated
using (public.kronia_is_diagnostic_admin());

drop policy if exists kronia_intelligence_admin_insert on public.kronia_intelligence_events;
create policy kronia_intelligence_admin_insert
on public.kronia_intelligence_events
for insert
to authenticated
with check (public.kronia_is_diagnostic_admin());
